"""Ordered language codes from official cards; see docs/model-metadata.md."""

QWEN_LANGUAGES = tuple(
    "zh en ja ko yue ar de fr es pt id it ru th vi tr hi ms nl sv da fi pl cs fil fa el hu mk ro".split()
)
PARAKEET_LANGUAGES = tuple(
    "en fr de es it pt ru bg hr cs da nl et fi el hu lv lt mt pl ro sk sl sv uk".split()
)
# The MOSS card publishes 50+ coverage but only names Chinese/English and
# the 14 challenge languages. Do not manufacture the remaining languages.
MOSS_LANGUAGES = tuple("zh en ja ko fr de it pt es ru th vi fil ur tr".split())
VOXCPM_LANGUAGES = tuple(
    "zh en ja ko ar my da nl fi fr de el he hi id it km lo ms no pl pt ru es sw sv fil th tr vi".split()
)

# Source speech languages (text targets have different coverage).
SEAMLESS_LANGUAGES = (
    "cmn",
    "eng",
    "jpn",
    "kor",
    "yue",
    "afr",
    "amh",
    "arb",
    "ary",
    "arz",
    "asm",
    "ast",
    "azj",
    "bel",
    "ben",
    "bos",
    "bul",
    "cat",
    "ceb",
    "ces",
    "ckb",
    "cmn_Hant",
    "cym",
    "dan",
    "deu",
    "ell",
    "est",
    "eus",
    "fin",
    "fra",
    "fuv",
    "gaz",
    "gle",
    "glg",
    "guj",
    "heb",
    "hin",
    "hrv",
    "hun",
    "hye",
    "ibo",
    "ind",
    "isl",
    "ita",
    "jav",
    "kam",
    "kan",
    "kat",
    "kaz",
    "kea",
    "khk",
    "khm",
    "kir",
    "lao",
    "lit",
    "ltz",
    "lug",
    "luo",
    "lvs",
    "mai",
    "mal",
    "mar",
    "mkd",
    "mlt",
    "mni",
    "mya",
    "nld",
    "nno",
    "nob",
    "npi",
    "nya",
    "oci",
    "ory",
    "pan",
    "pbt",
    "pes",
    "pol",
    "por",
    "ron",
    "rus",
    "slk",
    "slv",
    "sna",
    "snd",
    "som",
    "spa",
    "srp",
    "swe",
    "swh",
    "tam",
    "tel",
    "tgk",
    "tgl",
    "tha",
    "tur",
    "ukr",
    "urd",
    "uzn",
    "vie",
    "xho",
    "yor",
    "zlm",
    "zul",
)
